name: Sample workflow to test GH Actions
on:
    - push

jobs:
    greet:
        name: Greet user
        runs-on: ubuntu-latest
        
        steps:
            - name: Greet the user
              run: echo "Hello world"
            
            
            - name: Multiline comment
              run: |
                echo This is the first line
                echo This is the second line
            
            
            
            - name: cowsay
              run: cowsay Mooo
