name: Sample workflow to test GH Actions
on:
    - push

jobs:
    greet:
        name: Greet user
        runs-on: ubuntu-latest

        env:
          USERNAME: Someone
        
        steps:
            - name: Greet the user
              env:
                USERNAME: Sachin Lobo
              run: echo "Hello world from $USERNAME"
            
            
            - name: Multiline comment
              run: |
                echo This is the first line
                echo This is the second line
            
            
            - name: Install cowsay
              run: sudo apt update -y && sudo apt install cowsay -y
            
            - name: cowsay
              run: cowsay Mooo
